name: Git Artwork SVG
on:
    schedule: # Execute every week
        - cron: '0 0 * * 0'
    # Lines below let you run workflow manually and on each commit (optional)
    workflow_dispatch:
jobs:
    build:
        name: Make gitartwork SVG
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: jasineri/gitartwork@v1
              with:
                  # Use this username's contribution graph
                  user_name: kzamanbd
                  # Text on contribution graph
                  text: KAMRUZZAMAN
            - uses: jasineri/simple-push-action@v1
