name: Git Artwork SVG
on:
    schedule: # Execute every 12 hours
        - cron: '* */12 * * *'
jobs:
    build:
        name: Make gitartwork SVG
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: jasineri/gitartwork@v1
              with:
                  # Use this username's contribution graph
                  user_name: kzamanbd
                  # Text on contribution graph
                  text: ZAMAN
            - uses: jasineri/simple-push-action@v1
